/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ipduffy.metadataminer.newGUI;

/**
 *
 * @author duffian
 */
import com.ipduffy.metadataminer.core.Document;
import java.util.ArrayList;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

public class pnlDocumentTable extends javax.swing.JPanel {

    /**
     * Creates new form pnlDocumentTable
     */
    public pnlDocumentTable() {
        initComponents();
    }
    
    public pnlDocumentTable(ArrayList<Document> theDocuments) {
        initComponents();
        mTableModel.addRows(theDocuments);
        
        tblDocument.getSelectionModel().addListSelectionListener(new ListSelectionListener(){
            public void valueChanged(ListSelectionEvent event) {
                updateFields();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        mTableModel = new com.ipduffy.metadataminer.table.DocumentTableModel();
        spDocumentTable = new javax.swing.JScrollPane();
        tblDocument = new javax.swing.JTable();
        lblFilename = new javax.swing.JLabel();
        lblPath = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        lblMD5 = new javax.swing.JLabel();
        txtMD5 = new javax.swing.JTextField();
        txtFileName = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        tblDocument.setModel(mTableModel);
        tblDocument.setColumnSelectionAllowed(true);
        spDocumentTable.setViewportView(tblDocument);
        tblDocument.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(spDocumentTable, gridBagConstraints);

        lblFilename.setText("File Name:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblFilename, gridBagConstraints);

        lblPath.setText("Path:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblPath, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtPath, gridBagConstraints);

        lblMD5.setText("MD5 Hash:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblMD5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtMD5, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(txtFileName, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void updateFields() {
        int theRow = tblDocument.getSelectedRow();
        Document theDocument = mTableModel.getDocumentAtRow(theRow);
        if (theDocument != null) {
            txtFileName.setText(theDocument.getFilename());
            txtMD5.setText(theDocument.getMd5());
            txtPath.setText(theDocument.getFullPath());
        } else {
            txtFileName.setText("");
            txtMD5.setText("");
            txtPath.setText("");
        }
        txtFileName.setCaretPosition(0);
        txtMD5.setCaretPosition(0);
        txtPath.setCaretPosition(0);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFilename;
    private javax.swing.JLabel lblMD5;
    private javax.swing.JLabel lblPath;
    private com.ipduffy.metadataminer.table.DocumentTableModel mTableModel;
    private javax.swing.JScrollPane spDocumentTable;
    private javax.swing.JTable tblDocument;
    private javax.swing.JTextField txtFileName;
    private javax.swing.JTextField txtMD5;
    private javax.swing.JTextField txtPath;
    // End of variables declaration//GEN-END:variables
}
