/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * DocumentInfoFrame.java
 *
 * Created on Jun 27, 2011, 8:38:34 PM
 */

package com.ipduffy.metadataminer.gui;


import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.io.File;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import com.ipduffy.metadataminer.core.*;
/**
 *
 * @author duffian
 */
public class DocumentInfoFrame extends javax.swing.JFrame {

    private JButton btnClose = null;
    private JButton btnOpen = null;

    private Document mDocument = null;

    /** Creates new form DocumentInfoFrame */
    public DocumentInfoFrame(Document aDocument) {
        initComponents();

        mDocument = aDocument;

        DocumentInfoPanel theDocumentInfoPanel = new DocumentInfoPanel(aDocument);
        getContentPane().add(theDocumentInfoPanel, java.awt.BorderLayout.CENTER);

        btnClose = new JButton("Close");
        btnOpen = new JButton("Open Document");
        JButton button[] = {btnOpen, btnClose};

        getRootPane().setDefaultButton(btnClose);

        ButtonPanel bp = new ButtonPanel(button);
        getContentPane().add(bp, java.awt.BorderLayout.SOUTH);

        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
    }

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {
        this.setVisible(false);
        this.dispose();
    }

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {
        if (Desktop.isDesktopSupported()) {
            if (mDocument != null) {
                try {
                    File theFile = new File(mDocument.getFullPath());
                    Desktop theDesktop = Desktop.getDesktop();
                    theDesktop.open(theFile);
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Could not open file " + mDocument.getFullPath(), "Error", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error: Invalid Document", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Your OS does not support this operation.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-573)/2, (screenSize.height-570)/2, 573, 570);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
