/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * mainWindow.java
 *
 * Created on May 14, 2011, 1:22:51 PM
 */

package com.ipduffy.metadataminer.gui;


import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import com.ipduffy.metadataminer.dao.*;

/**
 *
 * @author duffian
 */
public class mainWindow extends javax.swing.JFrame implements DBConnectionListener {

    SearchFrame searchFrame = null;
    private ReportsPopupMenu mReportsPopupMenu = null;

    /** Creates new form mainWindow */
    public mainWindow() {
        initComponents();
        DBConnectionManager.addConnectionListener(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnNewWorkspace = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        btnReports = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        btnExit = new javax.swing.JButton();
        mainPanel1 = new com.ipduffy.metadataminer.gui.mainPanel();
        statusPanel1 = new com.ipduffy.metadataminer.gui.StatusPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Metadata Miner");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);
        jToolBar1.setMargin(new java.awt.Insets(5, 5, 5, 5));

        btnNewWorkspace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ipduffy/metadataminer/images/application_add.png"))); // NOI18N
        btnNewWorkspace.setText("New");
        btnNewWorkspace.setToolTipText("Create a new Metadata Miner workspace");
        btnNewWorkspace.setFocusable(false);
        btnNewWorkspace.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNewWorkspace.setMaximumSize(new java.awt.Dimension(54, 38));
        btnNewWorkspace.setMinimumSize(new java.awt.Dimension(54, 38));
        btnNewWorkspace.setPreferredSize(new java.awt.Dimension(54, 38));
        btnNewWorkspace.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnNewWorkspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewWorkspaceActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNewWorkspace);

        btnOpen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ipduffy/metadataminer/images/connect.png"))); // NOI18N
        btnOpen.setText("Open");
        btnOpen.setToolTipText("Open a saved Metadata Miner workspace");
        btnOpen.setFocusable(false);
        btnOpen.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpen.setMaximumSize(new java.awt.Dimension(54, 38));
        btnOpen.setMinimumSize(new java.awt.Dimension(54, 38));
        btnOpen.setPreferredSize(new java.awt.Dimension(54, 38));
        btnOpen.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOpen);

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ipduffy/metadataminer/images/application_put.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.setToolTipText("Save current Metadata Miner workspace");
        btnSave.setEnabled(false);
        btnSave.setFocusable(false);
        btnSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave.setMaximumSize(new java.awt.Dimension(54, 38));
        btnSave.setMinimumSize(new java.awt.Dimension(54, 38));
        btnSave.setPreferredSize(new java.awt.Dimension(54, 38));
        btnSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSave);

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ipduffy/metadataminer/images/magnifier.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.setToolTipText("Search current Metadata Miner workspace");
        btnSearch.setEnabled(false);
        btnSearch.setFocusable(false);
        btnSearch.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSearch.setMaximumSize(new java.awt.Dimension(54, 38));
        btnSearch.setMinimumSize(new java.awt.Dimension(54, 38));
        btnSearch.setPreferredSize(new java.awt.Dimension(54, 38));
        btnSearch.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSearch);

        btnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ipduffy/metadataminer/images/chart_bar.png"))); // NOI18N
        btnReports.setText("Reports");
        btnReports.setToolTipText("Create reports");
        btnReports.setEnabled(false);
        btnReports.setFocusable(false);
        btnReports.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnReports.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });
        jToolBar1.add(btnReports);
        jToolBar1.add(jSeparator1);

        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ipduffy/metadataminer/images/disconnect.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.setFocusable(false);
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setMaximumSize(new java.awt.Dimension(54, 38));
        btnExit.setMinimumSize(new java.awt.Dimension(54, 38));
        btnExit.setPreferredSize(new java.awt.Dimension(54, 38));
        btnExit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExit);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(mainPanel1, java.awt.BorderLayout.CENTER);
        getContentPane().add(statusPanel1, java.awt.BorderLayout.PAGE_END);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-420)/2, (screenSize.height-227)/2, 420, 227);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewWorkspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewWorkspaceActionPerformed
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            if (chooser.getSelectedFile() != null) {
                DBConnectionManager.createConnection(chooser.getSelectedFile(), true);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid database file selected.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnNewWorkspaceActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        DBConnectionManager.closeDBConnection();
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        // Open an HSQLDB that contains a previous workspace
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showOpenDialog(this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            if (chooser.getSelectedFile() != null) {
                DBConnectionManager.createConnection(chooser.getSelectedFile(), false);
                if (DBConnectionManager.isConnected()) {
                    JOptionPane.showMessageDialog(this, "File opened successfully.", "Success", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    JOptionPane.showMessageDialog(this, "Error opening database file.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnOpenActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        try {
            QueryFactory theQueryFactory = DBConnectionManager.getQueryFactory();
            theQueryFactory.saveDB();
            JOptionPane.showMessageDialog(this, "Database saved.", "Saved", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception e) {
            System.out.println("Error saving database: " + e.toString());
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        if (searchFrame == null) {
            searchFrame = new SearchFrame();
        }
        searchFrame.setVisible(true);
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        if (mReportsPopupMenu == null) {
            mReportsPopupMenu = new ReportsPopupMenu();
        }

        mReportsPopupMenu.show(btnReports, 0, btnReports.getHeight());
    }//GEN-LAST:event_btnReportsActionPerformed

    public void connected(boolean connected) {
        btnSearch.setEnabled(connected);
        btnReports.setEnabled(connected);
        btnSave.setEnabled(connected);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnNewWorkspace;
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnReports;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar jToolBar1;
    private com.ipduffy.metadataminer.gui.mainPanel mainPanel1;
    private com.ipduffy.metadataminer.gui.StatusPanel statusPanel1;
    // End of variables declaration//GEN-END:variables

}
