/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchPanel.java
 *
 * Created on Jun 1, 2011, 8:03:03 PM
 */

package com.ipduffy.metadataminer.gui;

/**
 *
 * @author duffian
 */
public class SearchPanel extends javax.swing.JPanel {


    /** Creates new form SearchPanel */
    public SearchPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblTitle = new javax.swing.JLabel();
        cmboxColumn = new javax.swing.JComboBox();
        cmboxComparator = new javax.swing.JComboBox();
        cmboxValue = new javax.swing.JTextField();

        setLayout(new java.awt.GridBagLayout());

        lblTitle.setText("Find all documents where:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = java.awt.GridBagConstraints.REMAINDER;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(lblTitle, gridBagConstraints);

        cmboxColumn.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "File name", "Title", "Comments", "Type", "File extension", "MD5", "Revision", "Editing time", "Application", "Creation Date", "Last Save Date", "Last Print Date", "Author", "Editor" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(cmboxColumn, gridBagConstraints);

        cmboxComparator.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "=", "!=", ">", ">=", "<", "<=", "contains", "starts with", "ends with" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(cmboxComparator, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        add(cmboxValue, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public String getSelectedSearchColumn() {
        switch(cmboxColumn.getSelectedIndex()) {
            case 0: return "filename";
            case 1: return "title";
            case 2: return "comments";
            case 3: return "type";
            case 4: return "extension";
            case 5: return "md5";
            case 6: return "revision";
            case 7: return "editingtime";
            case 8: return "application";
            case 9: return "creationdate";
            case 10: return "lastsavedate";
            case 11: return "lastprintdate";
            case 12: return "author";
            case 13: return "editor";
        }
        return null;
    }

    public String getSearchComparator() {
        return cmboxComparator.getSelectedItem().toString();
    }

    public String getSearchValue() {
        return cmboxValue.getText();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cmboxColumn;
    private javax.swing.JComboBox cmboxComparator;
    private javax.swing.JTextField cmboxValue;
    private javax.swing.JLabel lblTitle;
    // End of variables declaration//GEN-END:variables

}
