/*
 * SearchResultsTablePanel.java
 *
 * Created on Jun 8, 2011, 8:26:38 PM
 */

package com.ipduffy.metadataminer.gui;

import com.ipduffy.metadataminer.core.*;
import com.ipduffy.metadataminer.table.*;
import java.util.ArrayList;
/**
 *
 * @author duffian
 */
public class SearchResultsTablePanel extends javax.swing.JPanel {


    /** Creates new form SearchResultsTablePanel */
    public SearchResultsTablePanel(ArrayList theList) {
        initComponents();
        tblModel.mData = theList;

        for (int i=0; i < tblModel.getColumnCount(); i++) {
            tblSearchData.setDefaultRenderer(tblSearchData.getColumnClass(i), new DocumentCellRenderer());
        }

        // Have the table sort when you click on a column header
        tblSearchData.setAutoCreateRowSorter(true);

        tblSearchData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DocumentTableMouseClicked(evt);
            }
        });
    }
    
    public SearchResultsTablePanel() {
        initComponents();
    }

    private void DocumentTableMouseClicked(java.awt.event.MouseEvent evt) {
        int selectedRow = tblSearchData.getSelectedRow();
        if ((evt.getModifiers() & evt.BUTTON3_MASK) == evt.BUTTON3_MASK) {
            
            if (selectedRow < 0) {
                return;
            } else {
                Document theDocument = tblModel.getDocumentAtRow(selectedRow);
                new DocumentTablePopupMenu(theDocument).show(this, evt.getX(), evt.getY());
            }
        } else if (evt.getClickCount() == 2 && tblSearchData.getSelectedRowCount() > 0) {
            Document theDocument = tblModel.getDocumentAtRow(selectedRow);
            if (theDocument != null) {
                try {
                    DocumentInfoFrame theDocumentInfoFrame = new DocumentInfoFrame(theDocument);
                    theDocumentInfoFrame.setVisible(true);
                } catch (Exception e) {
                    System.out.println("Error display document details for " + theDocument.getFilename());
                } finally {
                    return;
                }
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tblModel = new com.ipduffy.metadataminer.table.DocumentTableModel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearchData = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        tblSearchData.setModel(tblModel);
        jScrollPane1.setViewportView(tblSearchData);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private com.ipduffy.metadataminer.table.DocumentTableModel tblModel;
    private javax.swing.JTable tblSearchData;
    // End of variables declaration//GEN-END:variables

}
