/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SearchResultsFrame.java
 *
 * Created on Jun 8, 2011, 8:25:10 PM
 */

package com.ipduffy.metadataminer.gui;

import com.ipduffy.metadataminer.core.Document;
import com.ipduffy.metadataminer.export.ExcelExporter;
import com.ipduffy.metadataminer.filefilter.XLSFileFilter;
import java.awt.event.ActionEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author duffian
 */
public class SearchResultsFrame extends javax.swing.JFrame {

    private JButton btnClose = null;
    private ArrayList mDocumentList = null;

    /** Creates new form SearchResultsFrame */
    public SearchResultsFrame(ArrayList<Document> theList) {
        mDocumentList = theList;
        
        initComponents();

        btnClose = new JButton("Close");

        JButton buttons[] = {btnClose};
        ButtonPanel bp = new ButtonPanel(buttons);
        getContentPane().add(bp, java.awt.BorderLayout.SOUTH);
        getRootPane().setDefaultButton(btnClose);

        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(ActionEvent arg0) {
                btnCloseActionPerformed(arg0);
            }
        });
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tbSearch = new javax.swing.JToolBar();
        btnExcel = new javax.swing.JButton();
        pnlDocumentTable = new com.ipduffy.metadataminer.newGUI.pnlDocumentTable(mDocumentList);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Search Results: Documents");

        tbSearch.setFloatable(false);
        tbSearch.setRollover(true);

        btnExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ipduffy/metadataminer/images/doc_excel_table.png"))); // NOI18N
        btnExcel.setText("Export");
        btnExcel.setToolTipText("Save to Excel");
        btnExcel.setFocusable(false);
        btnExcel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExcel.setMaximumSize(new java.awt.Dimension(54, 38));
        btnExcel.setMinimumSize(new java.awt.Dimension(54, 38));
        btnExcel.setPreferredSize(new java.awt.Dimension(54, 38));
        btnExcel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });
        tbSearch.add(btnExcel);

        getContentPane().add(tbSearch, java.awt.BorderLayout.PAGE_START);
        getContentPane().add(pnlDocumentTable, java.awt.BorderLayout.CENTER);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-651)/2, (screenSize.height-331)/2, 651, 331);
    }// </editor-fold>//GEN-END:initComponents

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.setFileFilter(new XLSFileFilter());
        int returnVal = chooser.showSaveDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File theOutputFile = chooser.getSelectedFile();

            // Make sure the file has the proper extension
            if (theOutputFile != null) {
                String theAbsolutePath = theOutputFile.getAbsolutePath();
                String theExtension = getFileExtension(theAbsolutePath);
                if (theExtension == null) {
                    theAbsolutePath += ".xls";
                    theOutputFile = new File(theAbsolutePath);
                } else if (theExtension.equalsIgnoreCase(".xls")) {
                    theAbsolutePath += ".xls";
                    theOutputFile = new File(theAbsolutePath);
                }
            }

            if (theOutputFile != null && mDocumentList != null) {
                ExcelExporter theExporter = new ExcelExporter(mDocumentList, theOutputFile);
                theExporter.writeExcelSpreadsheet();
                JOptionPane.showMessageDialog(this, "Excel spreadsheet saved.", "Save Successful", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Invalid Excel output file selected.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnExcelActionPerformed

    private String getFileExtension(String aFileName) {
        int index = aFileName.lastIndexOf(".");
        if (index >= 0) {
            String theExtension = aFileName.substring(index);
            return theExtension;
        }
        return null;
    }

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcel;
    private com.ipduffy.metadataminer.newGUI.pnlDocumentTable pnlDocumentTable;
    private javax.swing.JToolBar tbSearch;
    // End of variables declaration//GEN-END:variables

}
